### PR TITLE
Use a gender-neutral pronoun when announcing rating

### PR DESCRIPTION
**Pull request by devinreams**
This changes the hard-coded "He" in "He rated it a 4" at https://github.com/nicksergeant/slacktappd/blob/master/index.js#L22

...that seems like the simplest solution to incorrectly saying "he" when a "she" drinks a beer. That is, until Untappd's API  gender to the [/user/info](https://untappd.com/api/docs#user_info) endpoint.

### CODE REVIEW

**Comment by lynnaloo** [comment]
:+1: 

-1 to the Untappd API for not including gender in `user/info`
-1 to whoever typed "he" and didn't think that would cause a problem with 50% of humans

**Comment by devinreams** [comment]
> -1 to the Untappd API for not including gender in user/info

I discussed that with @gregavola recently, actually. As I understand it, since there are privacy implications, it would require properly making it so apps can ask for permission to _know_ gender identification. That takes things down a bit of a rabbit hole...

@nicksergeant Is this PR ok by you?

**Comment by nicksergeant** [comment]
Yeah! This is great, no idea how I missed this PR 10 months ago...

**Comment by devinreams** [comment]
Thank you!

**Pull request merged**
